export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const LOGOUT_USER = 'LOGOUT_USER';

export const FETCH_CAPABILITIES_PENDING = 'FETCH_CAPABILITIES_PENDING';
export const FETCH_CAPABILITIES_FULFILLED = 'FETCH_CAPABILITIES_FULFILLED';
export const FETCH_CAPABILITIES_REJECTED = 'FETCH_CAPABILITIES_REJECTED';
export const POST_EXPENSE_SECOND_CATEGORY = 'POST_EXPENSE_SECOND_CATEGORY';

export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';

export const REMOVE_PERMISSION_FROM_USER = 'REMOVE_PERMISSION_FROM_USER';

export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const GET_CURRENT_CATEGORY = 'GET_CURRENT_CATEGORY';


export const ADD_NEW_REQUEST = 'ADD_NEW_REQUEST';

export const POST_NEW_REQUEST_PENDING = 'POST_NEW_REQUEST_PENDING';
export const POST_NEW_REQUEST_FULFILLED = 'POST_NEW_REQUEST_FULFILLED';
export const POST_NEW_REQUEST_REJECTED = 'POST_NEW_REQUEST_REJECTED';

export const POST_NEW_COMMENT_PENDING = 'POST_NEW_COMMENT_PENDING';
export const POST_NEW_COMMENT_FULFILLED = 'POST_NEW_COMMENT_FULFILLED';
export const POST_NEW_COMMENT_REJECTED = 'POST_NEW_COMMENT_REJECTED';

export const POST_NEW_EXPENSE_PENDING = 'POST_NEW_EXPENSE_PENDING';
export const POST_NEW_EXPENSE_FULFILLED = 'POST_NEW_EXPENSE_FULFILLED';
export const POST_NEW_EXPENSE_REJECTED = 'POST_NEW_EXPENSE_REJECTED';


export const SET_CURRENT_CAPABILITY = 'SET_CURRENT_CAPABILITY';
export const GET_CURRENT_CAPABILITY = 'GET_CURRENT_CAPABILITY';
export const SET_CURRENT_CATEGORY_MANAGER = 'SET_CURRENT_CATEGORY_MANAGER';
export const SET_CURRENT_REQUEST_MANAGER = 'SET_CURRENT_REQUEST_MANAGER';

export const POST_MANAGER_RESPONSE_PENDING = 'POST_MANAGER_RESPONSE_PENDING';
export const POST_MANAGER_RESPONSE_FULFILLED = 'POST_MANAGER_RESPONSE_FULFILLED';
export const POST_MANAGER_RESPONSE_REJECTED = 'POST_MANAGER_RESPONSE_REJECTED';

export const POST_REQUEST_MANAGER_RESPONSE_PENDING = 'POST_REQUEST_MANAGER_RESPONSE_PENDING';
export const POST_REQUEST_MANAGER_RESPONSE_FULFILLED = 'POST_REQUEST_MANAGER_RESPONSE_FULFILLED';
export const POST_REQUEST_MANAGER_RESPONSE_REJECTED = 'POST_REQUEST_MANAGER_RESPONSE_REJECTED';

export const POST_MARK_COMMENT_READ_PENDING = 'POST_MARK_COMMENT_READ_PENDING';
export const POST_MARK_COMMENT_READ_FULFILLED = 'POST_MARK_COMMENT_READ_FULFILLED';
export const POST_MARK_COMMENT_READ_REJECTED = 'POST_MARK_COMMENT_READ_REJECTED';

export const POST_MARK_REQUEST_READ_PENDING = 'POST_MARK_REQUEST_READ_PENDING';
export const POST_MARK_REQUEST_READ_FULFILLED = 'POST_MARK_REQUEST_READ_FULFILLED';
export const POST_MARK_REQUEST_READ_REJECTED = 'POST_MARK_REQUEST_READ_REJECTED';

export const FILTER_REQUESTS = 'FILTER_REQUESTS';

export const POST_CHANGE_BUDGET_PENDING = 'POST_CHANGE_BUDGET_PENDING';
export const POST_CHANGE_BUDGET_FULFILLED = 'POST_CHANGE_BUDGET_FULFILLED';
export const POST_CHANGE_BUDGET_REJECTED = 'POST_CHANGE_BUDGET_REJECTED';

export const FETCH_ALL_USERS_PENDING = 'FETCH_ALL_USERS_PENDING';
export const FETCH_ALL_USERS_FULFILLED = 'FETCH_ALL_USERS_FULFILLED';
export const FETCH_ALL_USERS_REJECTED = 'FETCH_ALL_USERS_REJECTED';

export const ADD_USER_TO_CAPABILITY_PENDING = 'ADD_USER_TO_CAPABILITY_PENDING';
export const ADD_USER_TO_CAPABILITY_FULFILLED = 'ADD_USER_TO_CAPABILITY_FULFILLED';
export const ADD_USER_TO_CAPABILITY_REJECTED = 'ADD_USER_TO_CAPABILITY_REJECTED';

export const DELETE_USER_TO_CAPABILITY_PENDING = 'DELETE_USER_TO_CAPABILITY_PENDING';
export const DELETE_USER_TO_CAPABILITY_FULFILLED = 'DELETE_USER_TO_CAPABILITY_FULFILLED';
export const DELETE_USER_TO_CAPABILITY_REJECTED = 'DELETE_USER_TO_CAPABILITY_REJECTED';

export const FETCH_ALL_MANAGERS_PENDING = 'FETCH_ALL_MANAGERS_PENDING';
export const FETCH_ALL_MANAGERS_FULFILLED = 'FETCH_ALL_MANAGERS_FULFILLED';
export const FETCH_ALL_MANAGERS_REJECTED = 'FETCH_ALL_MANAGERS_REJECTED';

export const POST_CAPABILITY_REQUEST_PENDING = 'POST_CAPABILITY_REQUEST_PENDING';
export const POST_CAPABILITY_REQUEST_FULFILLED = 'POST_CAPABILITY_REQUEST_FULFILLED';
export const POST_CAPABILITY_REQUEST_REJECTED = 'POST_CAPABILITY_REQUEST_REJECTED';